name: test_gpt_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.1
  image: ^4.1.7
  image_picker: ^1.1.0
  intl: ^0.19.0
  logger: ^2.2.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  rename: ^3.0.2

flutter:
  uses-material-design: true
