name: clean_architecture_biv
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.2
  dartx: ^1.2.0
  decimal: ^2.3.3
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_secure_storage: ^9.0.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  image: ^4.1.7
  image_picker: ^1.1.0
  intl: ^0.19.0
  logger: ^2.2.0
  package_info_plus: ^7.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  tuple: ^2.0.2

dev_dependencies:
  flutter_flavorizr: ^2.2.3
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flavorizr:
  flavors:
    dev:
      app:
        name: "Biv App"

      android:
        applicationId: "com.biv.clean_architecture_dev"
      ios:
        bundleId: "com.biv.clean_architecture_dev"
      macos:
        bundleId: "com.biv.clean_architecture_dev"
    stg:
      app:
        name: "Biv App STG"
      android:
        applicationId: "com.biv.clean_architecture_stg"
      ios:
        bundleId: "com.biv.clean_architecture_stg"
      macos:
        bundleId: "com.biv.clean_architecture_stg"
